// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "translator",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "translator",
            targets: ["AppModule"],
            bundleIdentifier: "hoangviet.translator",
            teamIdentifier: "JRSZ4688V4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "speech recognition"),
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .fileAccess(.downloadsFolder, mode: .readWrite),
                .speechRecognition(purposeString: "speech recognition")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("ML")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)